# Generated by Django 4.0.5 on 2022-06-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
